- id: c38f98dd27fe485a80f8d22a8dcf7e4e
  alias: Home Assistant started
  trigger:
  - event: start
    platform: homeassistant
  action:
  - data_template:
      message: Home Assistant started {{now().strftime('%Y-%m-%d - %H:%M:%S')}}
    service: notify.ios_jans_phone
  - data:
      message: Home Assistant ist jetzt aktiv
    service: notify.ios_jans_ipad
- id: '1539785773973'
  alias: HA shutdown
  trigger:
  - event: shutdown
    platform: homeassistant
  condition: []
  action:
  - data:
      message: Home assistant shutting down
    service: notify.ios_jans_phone
