- id: c38f98dd27fe485a80f8d22a8dcf7e4e
  alias: Home Assistant started
  trigger:
  - event: start
    platform: homeassistant
  action:
  - data_template:
      message: Home Assistant started {{now().strftime('%Y-%m-%d - %H:%M:%S')}}
    service: notify.ios_jans_phone
  - data:
      message: Home Assistant ist jetzt aktiv
    service: notify.ios_jans_ipad
- id: '1539785773973'
  alias: HA shutdown
  trigger:
  - event: shutdown
    platform: homeassistant
  condition: []
  action:
  - data:
      message: Home assistant shutting down
    service: notify.ios_jans_phone
- id: dismiss
  alias: 'iOS Action: Dismiss Alarm'
  trigger:
  - event_data:
      actionName: IGNORE_ALARM
    event_type: ios.notification_action_fired
    platform: event
  action:
  - data:
      message: Alarm dismissed from Phone notification
      title: Alarm ignored
    service: persistent_notification.create
- id: disable
  alias: 'iOS Action: Disable Alarm'
  trigger:
  - event_data:
      actionName: DISABLE_ALARM
    event_type: ios.notification_action_fired
    platform: event
  action:
  - data:
      code: 1234
      entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_disarm
- id: '1551092301620'
  alias: 'iOS Widget: Arm Alarm'
  trigger:
  - event_data:
      actionName: Arm Alarm
    event_type: ios.action_fired
    platform: event
  condition: []
  action:
  - data:
      code: 1234
      entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_arm_away
- id: '1551092372349'
  alias: 'iOS Widget: Disarm Alarm'
  trigger:
  - event_data:
      actionName: Disarm Alarm
    event_type: ios.action_fired
    platform: event
  condition: []
  action:
  - data:
      code: 1234
      entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_disarm
