- id: c38f98dd27fe485a80f8d22a8dcf7e4e
  alias: Home Assistant started
  trigger:
  - event: start
    platform: homeassistant
  action:
  - data_template:
      message: Home Assistant started {{now().strftime('%Y-%m-%d - %H:%M:%S')}}
      data:
        tag: ha-system
    service: notify.mobile_app_iphone12pro_olbrecht_net
  - data:
      message: Home Assistant ist jetzt aktiv
      data:
        tag: ha-system
    service: notify.mobile_app_ipad_olbrecht_net
  mode: single
- id: '1539785773973'
  alias: HA shutdown
  trigger:
  - event: shutdown
    platform: homeassistant
  condition: []
  action:
  - data:
      message: Home assistant shutting down
      data:
        tag: ha-system
    service: notify.mobile_app_iphone12pro_olbrecht_net
  mode: single
- id: '1572215956106'
  alias: Arm alarm when no-one is home
  description: ''
  trigger:
  - entity_id: binary_sensor.someone_home
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      code: 1234
      entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_arm_away
  - scene: scene.everything_off
- id: '1572215956107'
  alias: Disarm alarm when someone is home
  description: ''
  trigger:
  - entity_id: binary_sensor.someone_home
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      code: 1234
      entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_disarm
- id: '1574619325241'
  alias: Turn off fan at 0600
  description: ''
  trigger:
  - at: 06:00:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: fan.dyson_pure_cool
    service: fan.turn_off
  mode: single
- id: '1574619944759'
  alias: Notify those at home when windows are open longer than 30 minutes
  description: ''
  trigger:
  - entity_id: binary_sensor.living_room_balcony_door_access_control_window_door_is_open
    for: 0:30:00
    platform: state
    to: 'on'
  - platform: state
    entity_id: binary_sensor.kids_room_window_access_control_window_door_is_open
    to: 'on'
    for: 0:30:00
  - platform: state
    entity_id: binary_sensor.master_bedroom_window_access_control_window_door_is_open
    to: 'on'
    for: 0:30:00
  - platform: state
    entity_id: binary_sensor.office_balcony_door_access_control_window_door_is_open
    to: 'on'
    for: 0:30:00
  condition:
  - condition: numeric_state
    entity_id: sensor.outside_temperature
    below: '8'
  action:
  - condition: state
    state: home
    entity_id: device_tracker.iphone12pro_olbrecht_net
  - data:
      message: Fenster {{ trigger.from_state.attributes.friendly_name }} schliessen.
    service: notify.mobile_app_iphone12pro_olbrecht_net
  - condition: state
    state: home
    entity_id: device_tracker.iphonexr_olbrecht_net
  - data:
      message: Fenster {{ trigger.from_state.attributes.friendly_name }} schliessen.
    service: notify.mobile_app_iphonexr_olbrecht_net
  mode: single
- id: '1602238482677'
  alias: Turn off Thermostat Master Bedroom
  description: ''
  trigger:
  - platform: time
    at: 05:00:00
  condition: []
  action:
  - device_id: 4bdf56c1c1e548cf89939d3660ac3363
    domain: climate
    entity_id: climate.thermostat_master_bedroom
    type: set_hvac_mode
    hvac_mode: 'off'
  mode: single
