homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  customize: !include customize.yaml    
  # Add an entry for each entity that you want to overwrite.
  packages: !include_dir_named packages
# Show links to resources in log and frontend
#introduction:


# Enables the frontend
frontend:
  javascript_version: latest
  #javascript_version: es5
#  themes: !include themes.yaml
  
system_log:

# Enables Apple iOS Support
ios:
#  push:

# Enable zeroconf
zeroconf:

# Enables configuration UI
config:

# Enable Home Assistant Cloud
cloud:

  
http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret base_url
  # SSL Configuration for Let'sEncrypt certs
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  trusted_networks:
    - 127.0.0.1
    - 192.168.0.0/24
  ip_ban_enabled: True
  login_attempts_threshold: 5

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history: !include history.yaml

# Configures recorder component     
recorder: !include recorder.yaml
# View all events in a logbook
logbook:

group: !include groups.yaml
automation: !include automations.yaml
device_tracker: !include device_tracker.yaml
script: !include scripts.yaml
zone: !include zones.yaml
map:

# Enable WoL Switch - cannot be merged via Package
wake_on_lan: 
  - mac: !secret readynas_mac
    broadcast_address: 192.168.0.255


# Workday binary sensor
binary_sensor:
  - platform: workday
    country: DE
    province: RP
   
system_health:

