homeassistant:
  customize: !include customize.yaml    
  # Add an entry for each entity that you want to overwrite.
  packages: !include_dir_named packages
  # Enable Home Assistant auth providers
  # Only required if using more than the default auth_provider
  auth_providers:
   - type: homeassistant  
   # - type: trusted_networks
   #   trusted_networks:
   #     - 192.168.0.0/24
  whitelist_external_dirs:
    - /config/www/snapshots

# Enables the frontend
frontend:

# Enable Home Assistant Default Configuration  
default_config:

# Enable the System log
system_log:
  # max_entries: 50 # Default Value 50

# Enable zeroconf
zeroconf:

# Enables configuration UI
config:

# Enable Home Assistant Cloud
cloud:

  
http:
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret base_url
  # SSL Configuration for Let'sEncrypt certs
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  #ip_ban_enabled: False
  #login_attempts_threshold: 5

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enable Person component
person:

group: !include groups.yaml

# Enable these to have GUI config for scripts and automation
automation: !include automations.yaml
script: !include scripts.yaml

# Zones for known locations
zone:

# Enable Map in Frontend
map:

# Enable WoL Switch - cannot be merged via Package
wake_on_lan: 
  - mac: !secret readynas_mac
    broadcast_address: 192.168.0.255

# Workday binary sensor
binary_sensor:
  - platform: workday
    country: DE
    province: RP

# Enable host system health   
system_health:

zwave: 
  usb_path: /dev/ttyAMA0
#  network_key: !secret zwave_network_key
  device_config: !include zwave_device_config.yaml