alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    delay_time: 20
    trigger_time: 15
    disarmed:
      trigger_time: 0
    armed_away:
      arming_time: 0
      delay_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0
    armed_night:
      arming_time: 0
      delay_time: 0

# Automation based on community example by @RezzZ: 
# https://community.home-assistant.io/t/manual-alarm-notification-trigger-variable/23154/11

input_text:
  alarm_trigger:
    name: Alarm Trigger
    initial: ""
    
automation:
# Trigger alarm on motion detected
  - alias: 'Alarm Triggers'
    initial_state: true
    trigger:
    - platform: state
      entity_id: binary_sensor.flur_sensor_motion
      to: 'on'
    condition:
    - condition: template
      value_template: "{{ not is_state('alarm_control_panel.home_alarm', 'disarmed') }}"
    action:
    - service: input_text.set_value
      data_template:
        entity_id: input_text.alarm_trigger
        value: >
          {% if states.input_text.alarm_trigger.state|length == 0 %}
            {{ trigger.from_state.attributes.friendly_name }}
          {% elif (states.input_text.alarm_trigger.state|length + trigger.from_state.attributes.friendly_name|length) < 100 %}
            {{ states.input_text.alarm_trigger.state }}, {{ trigger.from_state.attributes.friendly_name }}
          {% else %}
            {{ states.input_text.alarm_trigger.state }}
          {% endif %}
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.home_alarm
# Notify when alarm is triggered
  - alias: 'Alarm Triggered Notification'
    initial_state: true
    trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'triggered'
    action:
    - service: camera.record
      target:
        entity_id: camera.living_room
      data:
        filename: '/media/Alarms/Living_Room_{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4'
    - service: camera.record
      target:
        entity_id: camera.kids_room
      data:
        filename: '/media/Alarms/Kids_Room_{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4'
    - service: camera.record
      target:
        entity_id: camera.office
      data:
        filename: '/media/Alarms/Office_{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4'
    - service: notify.mobile_app_iphone12pro_olbrecht_net
      data:
        title: "Home Alarm triggered"
        message: "Trigger: {{ states.input_text.alarm_trigger.state }}"
        data:
          push:
            sound:
              # iOS Critical Notification
              critical: 1
              name: default
              volume: 0.1 # 0.0 to 1.0
          entity_id: camera.living_room
          actions:
            - action: "DISABLE_ALARM"
              title: 'Disable Alarm'
              activationMode: 'background'
              authenticationRequired: true
              destructive: true
            - action: "IGNORE_ALARM"
              title: 'Ignore Alarm'
              activationMode: 'background'
              authenticationRequired: false
              destructive: false
            - action: "URI"
              title: "Open Recordings"
              uri: "/media-browser"
          tag: "alarm-notification"
# Notify when Home Alarm gets disabled
  - alias: 'Alarm Disarmed Notification'
    initial_state: true
    trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'disarmed'
    action:
    - service: notify.mobile_app_iphone12pro_olbrecht_net
      data:
        message: "Alarm disarmed (resetting trigger: {{ states.input_text.alarm_trigger.state }})"
        data:
          tag: "alarm-notification"
    - service: input_text.set_value
      data_template:
        entity_id: input_text.alarm_trigger
        value: ''

## Catch automations for notification actions
# Dismiss alert and cancel notification on all devices
  - alias: 'Dismiss Alarm'
    initial_state: true
    trigger:
    - event_data:
        action: IGNORE_ALARM
      event_type: mobile_app_notification_action
      platform: event
    action:
    - data:
        message: Alarm dismissed from Phone notification
        title: Alarm ignored
      service: persistent_notification.create
    - service: notify.parents
      data:
        message: "clear_notification"
        data:
          tag: "alarm-notification"
# Disable Alarm
  - alias: 'Disable Alarm'
    initial_state: true
    trigger:
    - event_data:
        action: DISABLE_ALARM
      event_type: mobile_app_notification_action
      platform: event
    action:
    - data:
        code: !secret alarm_code
        entity_id: alarm_control_panel.home_alarm
      service: alarm_control_panel.alarm_disarm
