#####################################################################
#    @package          :     alexa_tts
#    @description      :     alexa_tts settings
#####################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'alexa_tts'

      hidden: &hidden
        <<: *customize
        hidden: true


    ################################################
    ## Input Text
    ################################################
    input_text.alexa_tts:
      icon: mdi:textbox


    ################################################
    ## Input Select
    ################################################
    input_select.alexa:
      icon: mdi:format-list-bulleted


    ################################################
    ## Input Number
    ################################################
    input_number.alexa_volume:
      icon: mdi:volume-high


#####################################################################
### Input Text
#####################################################################
input_text:
  alexa_tts:
    name: Alexa TTS
    initial: Hello


#####################################################################
### Input Number
#####################################################################
input_number:
  alexa_volume:
    name: Alexa Volume
    initial: 4
    min: 1
    max: 10
    step: 1


#####################################################################
### Input Select
#####################################################################
input_select:
  alexa:
    name: Alexa
    options:
      - None
      - Büro
      - Schlafzimmer
      - Wohnzimmer
      - Badezimmer

    initial: None
    icon: mdi:target


#####################################################################
### Automation
#####################################################################
automation:
  ## Announce what is typed as input
  - alias: Alexa TTS
    trigger:
      platform: state
      entity_id: input_select.alexa
    action:
      - service: media_player.volume_set
        data_template:
          entity_id: >
            {% if is_state('input_select.alexa', 'Büro') %}
              media_player.echo
            {% elif is_state('input_select.alexa', 'Schlafzimmer') %}
              media_player.echo_dot
            {% elif is_state('input_select.alexa', 'Wohnzimmer') %}
              media_player.sonos_beam
            {% elif is_state('input_select.alexa', 'Badezimmer') %}
              media_player.sonos_one
            {% elif is_state('input_select.alexa', 'None') %}
              false
            {% endif %}
          volume_level: '{{ states.input_number.alexa_volume.state | float /10 }}'
      - service: media_player.alexa_tts
        data_template:
          entity_id: >
            {% if is_state('input_select.alexa', 'Büro') %}
              media_player.echo
            {% elif is_state('input_select.alexa', 'Schlafzimmer') %}
              media_player.echo_dot
            {% elif is_state('input_select.alexa', 'Wohnzimmer') %}
              media_player.sonos_beam
            {% elif is_state('input_select.alexa', 'Badezimmer') %}
              media_player.sonos_one
            {% elif is_state('input_select.alexa', 'None') %}
              false
            {% endif %}
          message: "{{  states.input_text.alexa_tts.state }}"

      - delay: '00:00:02'

      - service: input_select.select_option
        data:
          entity_id: input_select.alexa
          option: None

