# This package adds my UniFi Video G3 Flex cameras via their RTSP streams
# as generic cameras.
#ffmpeg:

camera:
  #- platform: ffmpeg
  #  input: rtsp://192.168.0.11:7447/5b0c41d8e4b01eb859f05913_2
    
  - platform: generic
    name: Living Room
    still_image_url: !secret unifi_video_living_room_still
    verify_ssl: false
    stream_source: rtsp://192.168.0.1:7447/iwjOHc0pSo8Og8w7
  - platform: generic
    name: Kids Room
    still_image_url: !secret unifi_video_kids_room_still
    verify_ssl: false    
    stream_source: rtsp://192.168.0.1:7447/b2c55QMk1ksRzRdS
# The following enables the Stream component which enables streaming the 
# camera H.264 stream data to a Google Cast device (e.g. Android TV or Google
# Home Hub).
#
# When opening the stream from a picture entity in Lovelace, it is common that
# the stream will not load on first try. This is because the stream component
# requires buffering three full B-frames before sending out data to the 
# endpoint. Depending on source camera this can take between 2 to 30 seconds.

stream:

input_boolean:
  baby_monitor:
    name: Baby Monitor
    initial: off
    icon: mdi:baby
    
automation:
- alias: Stream Baby Monitor
  initial_state: 'true'
  trigger:
  - entity_id: input_boolean.baby_monitor
    platform: state
    to: 'on'
  condition: []
  action:
  - data_template:
      entity_id: camera.kids_room
      media_player: media_player.55pos9002
    service: camera.play_stream
- alias: Stop Baby Monitor
  initial_state: 'true'
  trigger:
  - entity_id: input_boolean.baby_monitor
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: media_player.android_tv
    service: media_player.turn_off
