binary_sensor:
  - platform: template
    sensors:
      front_door:
        friendly_name: Apartment Door
        device_class: door
        icon_template: >
          {% if is_state('sensor.fibaro_apartment_door_access_control', '22') %}
            mdi:door-open
          {% else %}
            mdi:door-closed
          {% endif %}
        value_template: >
          {% if is_state('sensor.fibaro_apartment_door_access_control', '22') %}
            true
          {% elif is_state('sensor.fibaro_apartment_door_access_control', '23') %}
            false
          {% else %}
            Error
          {% endif %}    
