automation:

# This automation sends me a notification with the estimated travel time to work
# every workday, using the workday binary sensor.

  - alias: 'Notification: Travel estimate to work'
    trigger:
    - at: 07:45:00
      platform: time
    condition:
      condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    action:
    - service: homeassistant.update_entity
      entity_id: sensor.time_to_work
    - data_template:
        message: The drive to work will take approximately {{ states.sensor.time_to_work.state
          }} minutes.
      service: notify.mobile_app_iphone12pro_olbrecht_net
