sensor:
# Google Travel Time
  - platform: google_travel_time
    api_key: !secret google_travel_time_key
    origin: !secret home_address
    destination: !secret work_address
    name: Time to Work
    scan_interval: 86400
  - platform: google_travel_time
    api_key: !secret google_travel_time_key
    origin: device_tracker.jans_phone
    destination: !secret home_address
    name: Jan to Home
    scan_interval: 86400

# Route to work
# Used to determine if Google is recommending an alternate route because of 
# traffic incidents
  - platform: template
    sensors:
      route_to_work_distance:
        friendly_name: 'Distance to work'
        unit_of_measurement: 'km'
        value_template: "{{ state_attr('sensor.time_to_work','distance').replace('km','')|float }}"
#        value_template: >-
#          {% if state_attr('sensor.time_to_work', 'distance')|float > 50 %}
#            Autobahn
#          {% elif state_attr('sensor.time_to_work', 'distance')|float < 50 %}
#            B271
#          {% else %}
#            failed
#          {% endif %}

automation:

# This automation sends me a notification with the estimated travel time to work
# every workday, using the workday binary sensor.

  - alias: 'Notification: Travel estimate to work'
    initial_state: 'true'
    trigger:
    - at: 07:45:00
      platform: time
    condition:
      condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    action:
    - service: homeassistant.update_entity
      entity_id: sensor.time_to_work
    - data_template:
        message: The drive to work will take approximately {{ states.sensor.time_to_work.state
          }} minutes.
      service: notify.ios_jans_phone

# This automation updates the morning commute sensor every 5 minutes each 
# morning

  - alias: 'Update morning commute sensor'
    initial_state: 'true'
    trigger:
    - minutes: /5
      seconds: 0
      platform: time_pattern
    condition:
    - after: 07:00:00
      before: 08:30:00
      condition: time
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'true'
    action:
    - data:
        entity_id: sensor.time_to_work
      service: homeassistant.update_entity

# This automation will alert me to the Google Travel Distance changing the 
# recommended route because of traffic conditions. In my case the usual route 
# is slightly longer then 52km

  - alias: 'Notification: Alert on traffic jam to work'
    initial_state: 'true'
    trigger:
    - below: '52'
      entity_id: sensor.route_to_work_distance
      platform: numeric_state
    condition: []
    action:
    - data:
        message: Stau auf der Autobahn, Alternative Route nehmen!
      service: notify.ios_jans_phone
  