# Enables Apple iOS Support
ios:
  push:
    categories:
      - name: Alarm
        identifier: 'ALARM'
        actions:
          - identifier: 'DISABLE_ALARM'
            title: 'Disable Alarm'
            activationMode: 'background'
            authenticationRequired: true
            destructive: true
            behavior: 'default'
          - identifier: 'IGNORE_ALARM'
            title: 'Ignore Alarm'
            activationMode: 'background'
            authenticationRequired: false
            destructive: false
            behavior: 'default'
      - name: Camera With Actions
        identifier: 'CAMERA'
        actions:
          - identifier: 'DISABLE_ALARM'
            title: 'Disable Alarm'
            activationMode: 'background'
            authenticationRequired: true
            destructive: true
          - identifier: 'IGNORE_ALARM'
            title: 'Ignore Alarm'
            activationMode: 'background'
            authenticationRequired: false
            destructive: false
script:
  request_location_update_jan:
    alias: Request Location Update Jan
    sequence:
    - data:
        message: request_location_update
      service: notify.ios_jans_phone
  request_location_update_kathrin:
    alias: Request Location Update kathrin
    sequence:
    - data:
        message: request_location_update
      service: notify.ios_kathrins_phone

###### The following has been stolen and compiled with the help of people in the Home Assistant Discord channel, especially @7even, @Ludeeus and @Sean!
sensor:

###### iOS APP PEDOMETER - STEP COUNTER ----------------------------------------
  # Let's take the step counter data from the iOS device tracker payload
  - platform: template
    sensors:
      ios_steps_walked_today:
        friendly_name: 'Step Counter'
        unit_of_measurement: 'Steps'
        icon_template: mdi:walk
        entity_id: device_tracker.iphonexsolbrechtnet_beta
        value_template: "{% set ped = state_attr('device_tracker.iphonexsolbrechtnet_beta', 'pedometer') %}{{ ped['number_of_steps'] | default(0) }}"

  # We need a statistics sensor to add up all the pedometer data
  - platform: statistics
    entity_id: sensor.ios_steps_walked_today
    name: iOS Steps Today Statistics #Total iOS Steps Today
    max_age:
      hours: 24

  # Let's take the statistics sensor and get the total number of steps.
  - platform: template
    sensors:
      ios_total_steps_walked_today:
        friendly_name: 'Steps Walked Today'
        unit_of_measurement: 'Steps'
        icon_template: mdi:walk
        entity_id: device_tracker.iphonexsolbrechtnet_beta
        value_template: "{{ state_attr('sensor.ios_steps_today_statistics_mean', 'total') | round(0) }}"

  # This takes the pedometer data and converts it to something more meaningful and metric :-)
  - platform: template
    sensors:
      ios_distance_walked_since_last_update:
        friendly_name: 'Distance Walked Since Last Update'
        unit_of_measurement: 'meters'
        icon_template: mdi:walk
        entity_id: device_tracker.iphonexsolbrechtnet_beta
        value_template: "{% set ped = state_attr('device_tracker.iphonexsolbrechtnet_beta', 'pedometer') %}{{ ped['distance'] | default(0) }}"

###### FLOORS CLIMBED UP/DOWN ----------------------------------------

  - platform: template
    sensors:
      ios_pedometer_floors_ascended:
        friendly_name: 'Floors Ascended'
        icon_template: mdi:stairs
        entity_id: device_tracker.iphonexsolbrechtnet_beta
        value_template: "{{states.device_tracker.iphonexsolbrechtnet_beta.attributes.pedometer.floors_ascended}}"

  - platform: template
    sensors:
      ios_pedometer_floors_descended:
        friendly_name: 'Floors Descended'
        icon_template: mdi:stairs
        entity_id: device_tracker.iphonexsolbrechtnet_beta
        value_template: "{{states.device_tracker.iphonexsolbrechtnet_beta.attributes.pedometer.floors_descended}}"

###### CURRENT ACTIVITY ----------------------------------------

  - platform: template
    sensors:
      ios_current_activity:
        friendly_name: 'iOS Current Activity'
        entity_id: device_tracker.iphonexsolbrechtnet_beta
        value_template: >-
          {% set act = state_attr('device_tracker.iphonexsolbrechtnet_beta', 'activity') %}
          {% set map = {
          "Stationary": "Stationary",
          "Walking": "Walking",
          "Running": "Running",
          "Automotive": "Automotive",
          "Cycling": "Cycling",
          "Unknown": "Unknown"
          } %}
          {{ map[act['types'][0]] if act['types'] else map['Unknown'] }}
        icon_template: >-
          {% set act = state_attr('device_tracker.iphonexsolbrechtnet_beta', 'activity') %}
          {% set map = {
          "Stationary": "mdi:sofa",
          "Walking": "mdi:walk",
          "Running": "mdi:run",
          "Automotive": "mdi:car",
          "Cycling": "mdi:bike",
          "Unknown": "mdi:help-circle"
          } %}
          {{ map[act['types'][0]] if act['types'] else map['Unknown'] }}


###### CURRENT ADDRESS ----------------------------------------

  # This provides the current address in a friendly style, for example "123 Flatbush Ave, Brooklyn, NY 11217"
  - platform: template
    sensors:
      ios_current_address:
        friendly_name: 'Location'
        icon_template: mdi:map-marker-radius
        entity_id: device_tracker.iphonexsolbrechtnet_beta
        value_template: "{% set loc = state_attr('device_tracker.iphonexsolbrechtnet_beta', 'location') %}{{ loc ['name'] }}, {{ loc ['locality'] }}, {{ loc ['postal_code'] }}, {{ loc ['administrative_area'] }}"
        
        

###### iOS CONNECTION TYPE ----------------------------------------

  # Are you on Wi-Fi or Cellular network?
  - platform: template
    sensors:
      ios_connection_type:
        friendly_name: 'Connection Type'
        icon_template: mdi:wifi
        entity_id: device_tracker.iphonexsolbrechtnet_beta
        value_template: "{% set conn = state_attr('device_tracker.iphonexsolbrechtnet_beta', 'connection') %}{{ '4G' if conn['type'] == 'Cellular' else 'Wi-Fi' }}"        

  # Track the AP
  - platform: template
    sensors:
      ios_connection_bssid:
        friendly_name: 'Connected AP'
        icon_template: mdi:wifi
        entity_id: device_tracker.iphonexsolbrechtnet_beta
        value_template: "{{states.device_tracker.iphonexsolbrechtnet_beta.attributes.connection.bssid}}"

  # This converts known access point BSSID MAC addresses to rough indoor locations.
  # Note that we have multiple BSSIDs for every location, as AP radios have different
  # BSSIDs for 2.4 and 5GHz radios.
  - platform: template
    sensors:
      indoor_location:
        friendly_name: 'Indoor Location'
        icon_template: mdi:home
        entity_id: sensor.ios_connection_bssid
        value_template:  >-
          {% if is_state('sensor.ios_connection_bssid', '82:2a:a8:d4:cf:d6') %}
            North East Offices
          {% elif  is_state('sensor.ios_connection_bssid', '92:2a:a8:d5:cf:d6') %}
            North East Offices
          {% elif  is_state('sensor.ios_connection_bssid', '82:2a:a8:d4:cd:ba') %}
            Dev Office
          {% elif  is_state('sensor.ios_connection_bssid', '82:2a:a8:d5:cd:ba') %}
            Dev Office
          {% elif  is_state('sensor.ios_connection_bssid', '82:2a:a8:d4:c6:6b') %}
            South West Offices
          {% elif  is_state('sensor.ios_connection_bssid', '92:2a:a8:d5:c6:6b') %}
            South West Offices
          {% elif  is_state('sensor.ios_connection_bssid', '82:2a:a8:d4:cd:87') %}
            Meeting Room
          {% elif  is_state('sensor.ios_connection_bssid', '92:2a:a8:d5:cd:87') %}
            Meeting Room
          {% elif  is_state('sensor.ios_connection_bssid', '82:2a:a8:d4:c5:ed') %}
            North West Offices
          {% elif  is_state('sensor.ios_connection_bssid', '92:2a:a8:d5:c5:ed') %}
            North West Offices
          {% elif  is_state('sensor.ios_connection_bssid', '82:2a:a8:5a:1d:2b') %}
            Living Room
          {% elif  is_state('sensor.ios_connection_bssid', '82:2a:a8:5b:1d:2b') %}
            Living Room
          {% elif  is_state('sensor.ios_connection_bssid', '82:2a:a8:9a:71:c8') %}
            Home Office
          {% elif  is_state('sensor.ios_connection_bssid', '82:2a:a8:9b:71:c8') %}
            Home Office
          {% elif  is_state('sensor.ios_connection_bssid', '82:2a:a8:9a:72:59') %}
            Master Bedroom
          {% elif  is_state('sensor.ios_connection_bssid', '82:2a:a8:9b:72:59') %}
            Master Bedroom
          {% elif  is_state('sensor.ios_connection_bssid', '04:18:d6:a0:bc:02') %}
            Marita's Living Room
          {% elif  is_state('sensor.ios_connection_bssid', '04:18:d6:a0:bc:03') %}
            Marita's Living Room
          {% elif  is_state('sensor.ios_connection_bssid', '04:18:d6:a0:ba:1f') %}
            Marita's Floor
          {% elif  is_state('sensor.ios_connection_bssid', '04:18:d6:a0:ba:20') %}
            Marita's Floor
          {% else %}
            Unknown
          {% endif %}
        
      
        
# SENSORS FOR DISPLAYING IN LOVELACE

# - type: entities
#   show_header_toggle: false
#   entities:
#     - sensor.ios_steps_walked_today
#     - sensor.ios_steps_today_statistics
#     - sensor.ios_total_steps_walked_today
#     - sensor.ios_distance_walked_since_last_update
#     - sensor.ios_pedometer_floors_ascended
#     - sensor.ios_pedometer_floors_descended
#     - sensor.ios_current_activity
#     - sensor.ios_current_address
#     - sensor.ios_connection_type      
#     - sensor.ios_connection_bssid

#######  Starting here are the automations to catch iOS actionable notifications and do something with them


automation:
  - alias: 'iOS Action: Dismiss Alarm'
    trigger:
    - event_data:
        actionName: IGNORE_ALARM
      event_type: ios.notification_action_fired
      platform: event
    action:
    - data:
        message: Alarm dismissed from Phone notification
        title: Alarm ignored
      service: persistent_notification.create
  - alias: 'iOS Action: Disable Alarm'
    trigger:
    - event_data:
        actionName: DISABLE_ALARM
      event_type: ios.notification_action_fired
      platform: event
    action:
    - data:
        code: !secret alarm_code
        entity_id: alarm_control_panel.home_alarm
      service: alarm_control_panel.alarm_disarm
  - alias: 'iOS Widget: Arm Alarm'
    trigger:
    - event_data:
        actionName: Arm Alarm
      event_type: ios.action_fired
      platform: event
    condition: []
    action:
    - data:
        code: 1234
        entity_id: alarm_control_panel.home_alarm
      service: alarm_control_panel.alarm_arm_away
  - alias: 'iOS Widget: Disarm Alarm'
    trigger:
    - event_data:
        actionName: Disarm Alarm
      event_type: ios.action_fired
      platform: event
    condition: []
    action:
    - data:
        code: !secret alarm_code
        entity_id: alarm_control_panel.home_alarm
      service: alarm_control_panel.alarm_disarm
  