# Enables Apple iOS Support
ios:
  push:
    categories:
      - name: Alarm
        identifier: 'ALARM'
        actions:
          - identifier: 'DISABLE_ALARM'
            title: 'Disable Alarm'
            activationMode: 'background'
            authenticationRequired: true
            destructive: true
            behavior: 'default'
          - identifier: 'IGNORE_ALARM'
            title: 'Ignore Alarm'
            activationMode: 'background'
            authenticationRequired: false
            destructive: false
            behavior: 'default'
      - name: Camera With Actions
        identifier: 'CAMERA'
        actions:
          - identifier: 'DISABLE_ALARM'
            title: 'Disable Alarm'
            activationMode: 'background'
            authenticationRequired: true
            destructive: true
          - identifier: 'IGNORE_ALARM'
            title: 'Ignore Alarm'
            activationMode: 'background'
            authenticationRequired: false
            destructive: false
      - name: Monitoring
        identifier: 'MONITORING'
        actions:
          - identifier: 'ACK_MONITORING'
            title: 'Acknowledge Alert'
            activationMode: 'background'
            authenticationRequired: false
            destructive: false
          - identifier: 'RESET_MONITORING'
            title: 'Reset Alert'
            activationMode: 'background'
            authenticationRequired: false
            destructive: true

script:
  request_location_update_jan:
    alias: Request Location Update Jan
    sequence:
    - data:
        message: request_location_update
      service: notify.mobile_app_iphonexs_olbrecht_net
  request_location_update_kathrin:
    alias: Request Location Update kathrin
    sequence:
    - data:
        message: request_location_update
      service: notify.ios_kathrins_phone


automation:
  - alias: 'iOS Action: Dismiss Alarm'
    initial_state: 'true'
    trigger:
    - event_data:
        actionName: IGNORE_ALARM
      event_type: ios.notification_action_fired
      platform: event
    action:
    - data:
        message: Alarm dismissed from Phone notification
        title: Alarm ignored
      service: persistent_notification.create
  - alias: 'iOS Action: Disable Alarm'
    initial_state: 'true'
    trigger:
    - event_data:
        actionName: DISABLE_ALARM
      event_type: ios.notification_action_fired
      platform: event
    action:
    - data:
        code: !secret alarm_code
        entity_id: alarm_control_panel.home_alarm
      service: alarm_control_panel.alarm_disarm
  - alias: 'iOS Widget: Arm Alarm'
    initial_state: 'true'
    trigger:
    - event_data:
        actionName: Arm Alarm
      event_type: ios.action_fired
      platform: event
    condition: []
    action:
    - data:
        code: !secret alarm_code
        entity_id: alarm_control_panel.home_alarm
      service: alarm_control_panel.alarm_arm_away
  - alias: 'iOS Widget: Disarm Alarm'
    initial_state: 'true'
    trigger:
    - event_data:
        actionName: Disarm Alarm
      event_type: ios.action_fired
      platform: event
    condition: []
    action:
    - data:
        code: !secret alarm_code
        entity_id: alarm_control_panel.home_alarm
      service: alarm_control_panel.alarm_disarm
  - alias: 'iOS Action: Reset Monitoring'
    initial_state: 'true'
    trigger:
    - event_data:
        actionName: RESET_MONITORING
      event_type: ios.notification_action_fired
      platform: event
    action:
    - data:
        value: ''
        entity_id: input_text.network_monitoring_trigger
      service: input_text.set_value
  - alias: 'Mobile App Action: Dismiss Alarm'
    initial_state: 'true'
    trigger:
    - event_data:
        actionName: IGNORE_ALARM
      event_type: mobile_app.notification_action_fired
      platform: event
    action:
    - data:
        message: Alarm dismissed from Phone notification
        title: Alarm ignored
      service: persistent_notification.create
  - alias: 'Mobile App Action: Disable Alarm'
    initial_state: 'true'
    trigger:
    - event_data:
        actionName: DISABLE_ALARM
      event_type: mobile_app.notification_action_fired
      platform: event
    action:
    - data:
        code: !secret alarm_code
        entity_id: alarm_control_panel.home_alarm
      service: alarm_control_panel.alarm_disarm
  - alias: 'Mobile App Widget: Arm Alarm'
    initial_state: 'true'
    trigger:
    - event_data:
        actionName: Arm Alarm
      event_type: mobile_app.action_fired
      platform: event
    condition: []
    action:
    - data:
        code: !secret alarm_code
        entity_id: alarm_control_panel.home_alarm
      service: alarm_control_panel.alarm_arm_away
  - alias: 'Mobile App Widget: Disarm Alarm'
    initial_state: 'true'
    trigger:
    - event_data:
        actionName: Disarm Alarm
      event_type: mobile_app.action_fired
      platform: event
    condition: []
    action:
    - data:
        code: !secret alarm_code
        entity_id: alarm_control_panel.home_alarm
      service: alarm_control_panel.alarm_disarm
  - alias: 'Mobile App Action: Reset Monitoring'
    initial_state: 'true'
    trigger:
    - event_data:
        actionName: RESET_MONITORING
      event_type: mobile_app.notification_action_fired
      platform: event
    action:
    - data:
        value: ''
        entity_id: input_text.network_monitoring_trigger
      service: input_text.set_value
  