# Enables Apple iOS Support
ios:
#  push:

script:
  request_location_update_jan:
    alias: Request Location Update Jan
    sequence:
    - data:
        message: request_location_update
      service: notify.ios_jans_phone
  request_location_update_kathrin:
    alias: Request Location Update kathrin
    sequence:
    - data:
        message: request_location_update
      service: notify.ios_kathrins_phone

automation:
  alias: Catch iOS action notification
  trigger:
  - event_type: ios.action_fired
    platform: event
  action:
  - data_template:
      message: 'Received action named {{ trigger.event.data.actionName }} from device {{ trigger.event.data.sourceDeviceID }} triggered from {{ trigger.event.data.triggerSource }}'
    service: notify.ios_jans_phone
