binary_sensor:
  - platform: ping
    scan_interval: 300
    name: unifi_dream_machine_pro
    host: 192.168.0.1
  - platform: ping
    scan_interval: 300
    name: unifi_switch_office
    host: 192.168.0.3
  - platform: ping
    scan_interval: 300
    name: unifi_ap_livingroom
    host: 192.168.0.6
  - platform: ping
    scan_interval: 300
    name: unifi_ap_master_bedroom
    host: 192.168.0.5
  - platform: ping
    scan_interval: 300
    name: unifi_ap_extender
    host: 192.168.0.7
  - platform: ping
    scan_interval: 300
    name: unifi_g3_flex_living_room
    host: 192.168.0.16
  - platform: ping
    scan_interval: 300
    name: unifi_g3_flex_kids_room
    host: 192.168.0.17
  - platform: ping
    scan_interval: 300
    name: sonos_beam_living_room
    host: 192.168.0.21
  - platform: ping
    scan_interval: 300
    name: sonos_play1_living_room_1
    host: 192.168.0.22
  - platform: ping
    scan_interval: 300
    name: sonos_play1_living_room_2
    host: 192.168.0.23
  - platform: ping
    scan_interval: 300
    name: sonos_play1_kids_room
    host: 192.168.0.24
  - platform: ping
    scan_interval: 300
    name: sonos_one_bathroom
    host: 192.168.0.25
  - platform: ping
    scan_interval: 300
    name: bosch_hsg636xs6
    host: 192.168.0.18
  - platform: ping
    scan_interval: 300
    name: ikea_tradfri_hub
    host: 192.168.0.13
  - platform: ping
    scan_interval: 300
    name: philips_hue_bridge
    host: 192.168.0.14
  - platform: ping
    scan_interval: 300
    name: raspi_homeassistant
    host: 192.168.0.10
  - platform: ping
    scan_interval: 300
    name: sw02
    host: 192.168.0.2
  - platform: ping
    scan_interval: 300
    name: snom_d765
    host: 192.168.2.2
  - platform: ping
    scan_interval: 300
    name: philips_55pos9002_lan
    host: 192.168.0.15
  - platform: ping
    scan_interval: 300
    name: dyson_pure_cool_link
    host: 192.168.0.39
  - platform: ping
    scan_interval: 300
    name: dyson_pure_humidify_cool
    host: 192.168.0.40
      
input_text:
  network_monitoring_trigger:
    name: Network Monitoring Trigger
    initial: ""
    
automation:
  - alias: 'Network Monitoring Triggers'
    initial_state: 'true'
    trigger:
    - platform: state
      entity_id: binary_sensor.sonos_one_bathroom
      to: 'off'
      for:
        minutes: 10
    - platform: state
      entity_id: binary_sensor.sonos_play1_kids_room
      to: 'off'
      for:
        minutes: 10
    - platform: state
      entity_id: binary_sensor.sonos_play1_living_room_1
      to: 'off'
      for:
        minutes: 10
    - platform: state
      entity_id: binary_sensor.sonos_play1_living_room_2
      to: 'off'
      for:
        minutes: 10
    - platform: state
      entity_id: binary_sensor.sonos_beam_living_room
      to: 'off'
      for:
        minutes: 10
    - platform: state
      entity_id: binary_sensor.snom_d765_phone
      to: 'off'
      for:
        minutes: 10
    - platform: state
      entity_id: binary_sensor.philips_hue_bridge
      to: 'off'
      for:
        minutes: 10
    - platform: state
      entity_id: binary_sensor.brother_mfc_l3770cdw
      to: 'off'
      for:
        minutes: 10
    - platform: state
      entity_id: binary_sensor.unifi_dream_machine_pro
      to: 'off'
      for:
        minutes: 10
    action:
    - service: input_text.set_value
      data_template:
        entity_id: input_text.network_monitoring_trigger
        value: >
          {% if states.input_text.network_monitoring_trigger.state|length == 0 %}
            {{ trigger.from_state.attributes.friendly_name }}
          {% elif (states.input_text.network_monitoring_trigger.state|length + trigger.from_state.attributes.friendly_name|length) < 100 %}
            {{ states.input_text.network_monitoring_trigger.state }}, {{ trigger.from_state.attributes.friendly_name }}
          {% else %}
            {{ states.input_text.network_monitoring_trigger.state }}
          {% endif %}
    - service: notify.mobile_app_iphone12pro_olbrecht_net
      data:
        title: "Network Monitoring Alert"
        message: "The device {{ states.input_text.network_monitoring_trigger.state }} is offline"
        data:
          push:
            category: monitoring
            sound:
              name: default
            thread-id: "monitoring"
            