device_tracker:
  - platform: unifi
    username: !secret unifi_user
    password: !secret unifi_password
    host: unifi.olbrecht.net
    track_new_devices: no
    detection_time: 180
    ssid_filter:
      - 'olbrecht.net'
  - platform: ping
    interval_seconds: 10
    hosts:
      Ping_UniFi_Cloud_Key: 192.168.0.4
      Ping_UniFi_Security_Gateway: 192.168.0.1
      Ping_UniFi_AP_LivingRoom: 192.168.0.5
      Ping_UniFi_AP_Office: 192.168.0.6
      Ping_UniFi_AP_Master_Bedroom: 192.168.0.7
      Ping_Unifi_G3_Flex_Living_Room: 192.168.0.51
      Ping_Unifi_G3_Flex_Kids_Room: 192.168.0.52
      Ping_Sonos_Beam_Living_Room: 192.168.0.45
      Ping_Sonos_Play1_Living_Room_1: 192.168.0.44
      Ping_Sonos_Play1_Living_Room_2: 192.168.0.43
      Ping_Sonos_Play1_Kids_Room: 192.168.0.42
      Ping_Sonos_One_Bathroom: 192.168.0.46
      Ping_Bosch_HSG636XS6: 192.168.0.41
      Ping_Philips_Hue_Bridge: 192.168.0.13
      Ping_RasPi_Observium: 192.168.0.10
      Ping_RasPi_HomeAssistant: 192.168.0.9
      Ping_SW01: 192.168.0.2
      Ping_SW02: 192.168.0.3
      Ping_SNOM_D765: 192.168.2.2
      Ping_Philips_55POS9002_LAN: 192.168.0.15
      Ping_Dyson_Pure_Cool_Link: 192.168.0.47
      Ping_RasPi_BTMonitor: 192.168.0.18
      Ping_FireTV_Office: 192.168.0.26
      Ping_Brother_MFC_L3770CDW: 192.168.0.17
      
      
sensor:
# Device tracker values are changed from home to Online/Offline
  - platform: template
    sensors:
      amazon_echo:
        value_template:  '{% if is_state("device_tracker.amazon_echo", "home") %} Online {% else %} Offline {%- endif %}'
      amazon_echo_dot:
        value_template:  '{% if is_state("device_tracker.amazon_echo_dot", "home") %} Online {% else %} Offline {%- endif %}'
      brother_mfc_l3770cdw:
        value_template:  '{% if is_state("device_tracker.ping_brother_mfc_l3770cdw", "home") %} Online {% else %} Offline {%- endif %}'
      bosch_hsg636xs6:
        value_template:  '{% if is_state("device_tracker.ping_bosch_hsg636xs6", "home") %} Online {% else %} Offline {%- endif %}'
      dyson_pure_cool_link:
        value_template:  '{% if is_state("device_tracker.ping_dyson_pure_cool_link", "home") %} Online {% else %} Offline {%- endif %}'
      firetv_stick_office:
        value_template:  '{% if is_state("device_tracker.ping_firetv_office", "home") %} Online {% else %} Offline {%- endif %}'
      philips_hue_bridge:
        value_template:  '{% if is_state("device_tracker.ping_philips_hue_bridge", "home") %} Online {% else %} Offline {%- endif %}'
      living_room_xbox_one:
        value_template:  '{% if is_state("device_tracker.living_room_xbox_one", "home") %} Online {% else %} Offline {%- endif %}'
      raspi_observium:
        value_template:  '{% if is_state("device_tracker.ping_raspi_observium", "home") %} Online {% else %} Offline {%- endif %}'
      raspi_homeassistant:
        value_template:  '{% if is_state("device_tracker.ping_raspi_homeassistant", "home") %} Online {% else %} Offline {%- endif %}'
      raspi_btmonitor:
        value_template:  '{% if is_state("device_tracker.ping_raspi_btmonitor", "home") %} Online {% else %} Offline {%- endif %}'
      snom_d765_phone:
        value_template:  '{% if is_state("device_tracker.ping_snom_d765", "home") %} Online {% else %} Offline {%- endif %}'
      sonos_play1_kids_room:
        value_template:  '{% if is_state("device_tracker.ping_sonos_play1_kids_room", "home") %} Online {% else %} Offline {%- endif %}'
      sonos_one_bathroom:
        value_template:  '{% if is_state("device_tracker.ping_sonos_one_bathroom", "home") %} Online {% else %} Offline {%- endif %}'
      sonos_beam_living_room:
        value_template:  '{% if is_state("device_tracker.ping_sonos_beam_living_room", "home") %} Online {% else %} Offline {%- endif %}'
      sonos_play1_living_room_1:
        value_template:  '{% if is_state("device_tracker.ping_sonos_play1_living_room_1", "home") %} Online {% else %} Offline {%- endif %}'
      sonos_play1_living_room_2:
        value_template:  '{% if is_state("device_tracker.ping_sonos_play1_living_room_2", "home") %} Online {% else %} Offline {%- endif %}'
      sw01:
        value_template:  '{% if is_state("device_tracker.ping_sw01", "home") %} Online {% else %} Offline {%- endif %}'
      sw02:
        value_template:  '{% if is_state("device_tracker.ping_sw02", "home") %} Online {% else %} Offline {%- endif %}'
      tv_living_room:
        value_template:  '{% if is_state("device_tracker.ping_philips_55pos9002_lan", "home") %} Online {% else %} Offline {%- endif %}'
      unifi_security_gateway:
        value_template:  '{% if is_state("device_tracker.ping_unifi_security_gateway", "home") %} Online {% else %} Offline {%- endif %}'
      unifi_cloud_key:
        value_template:  '{% if is_state("device_tracker.ping_unifi_cloud_key", "home") %} Online {% else %} Offline {%- endif %}'
      unifi_ap_livingroom:
        value_template:  '{% if is_state("device_tracker.ping_unifi_ap_livingroom", "home") %} Online {% else %} Offline {%- endif %}'
      unifi_ap_office:
        value_template:  '{% if is_state("device_tracker.ping_unifi_ap_office", "home") %} Online {% else %} Offline {%- endif %}'
      unifi_ap_master_bedroom:
        value_template:  '{% if is_state("device_tracker.ping_unifi_ap_master_bedroom", "home") %} Online {% else %} Offline {%- endif %}'



input_text:
  network_monitoring_trigger:
    name: Network Monitoring Trigger
    initial: ""
    
automation:
  - alias: 'Network Monitoring Triggers'
    initial_state: 'true'
    trigger:
    - platform: state
      entity_id: sensor.sonos_one_bathroom
      to: 'Offline'
    - platform: state
      entity_id: sensor.sonos_play1_kids_room
      to: 'Offline'
    - platform: state
      entity_id: sensor.sonos_play1_living_room_1
      to: 'Offline'
    - platform: state
      entity_id: sensor.sonos_play1_living_room_2
      to: 'Offline'
    - platform: state
      entity_id: sensor.sonos_beam_living_room
      to: 'Offline'
    - platform: state
      entity_id: sensor.snom_d765_phone
      to: 'Offline'
    - platform: state
      entity_id: sensor.philips_hue_bridge
      to: 'Offline'
    - platform: state
      entity_id: sensor.brother_mfc_l3770cdw
      to: 'Offline'
    - platform: state
      entity_id: sensor.amazon_echo
      to: 'Offline'
    - platform: state
      entity_id: sensor.amazon_echo_dot
      to: 'Offline'
    - platform: state
      entity_id: sensor.unifi_security_gateway
      to: 'Offline'
    - platform: state
      entity_id: sensor.raspi_btmonitor
      to: 'Offline'
    - platform: state
      entity_id: sensor.raspi_observium
      to: 'Offline'
    action:
    - service: input_text.set_value
      data_template:
        entity_id: input_text.network_monitoring_trigger
        value: >
          {% if states.input_text.network_monitoring_trigger.state|length == 0 %}
            {{ trigger.from_state.attributes.friendly_name }}
          {% elif (states.input_text.network_monitoring_trigger.state|length + trigger.from_state.attributes.friendly_name|length) < 100 %}
            {{ states.input_text.network_monitoring_trigger.state }}, {{ trigger.from_state.attributes.friendly_name }}
          {% else %}
            {{ states.input_text.network_monitoring_trigger.state }}
          {% endif %}
    - service: notify.mobile_app_iphonexs_olbrecht_net
      data:
        title: "Network Monitoring Alert"
        message: "The device {{ states.input_text.network_monitoring_trigger.state }} is offline"
        data:
          push:
            category: monitoring
            sound:
              name: default
            thread-id: "monitoring"
            