device_tracker:
  - platform: ping
    interval_seconds: 60
    hosts:
      ping_unifi_dream_machine_pro: 192.168.0.1
      ping_unifi_switch_office: 192.168.0.3
      ping_unifi_ap_livingroom: 192.168.0.6
      ping_unifi_ap_master_bedroom: 192.168.0.4
      ping_unifi_ap_office: 192.168.0.5
      ping_unifi_ap_extender: 192.168.0.7
      ping_unifi_g3_flex_living_room: 192.168.0.16
      ping_unifi_g3_flex_kids_room: 192.168.0.17
      ping_sonos_beam_living_room: 192.168.0.21
      ping_sonos_play1_living_room_1: 192.168.0.22
      ping_sonos_play1_living_room_2: 192.168.0.23
      ping_sonos_play1_kids_room: 192.168.0.24
      ping_sonos_one_bathroom: 192.168.0.25
      ping_bosch_hsg636xs6: 192.168.0.18
      ping_ikea_tradfri_hub: 192.168.0.13
      ping_philips_hue_bridge: 192.168.0.14
      ping_raspi_homeassistant: 192.168.0.10
      ping_sw02: 192.168.0.2
      ping_snom_d765: 192.168.2.2
      ping_philips_55pos9002_lan: 192.168.0.15
      ping_dyson_pure_cool_link: 192.168.0.19
      
sensor:
# Device tracker values are changed from home to Online/Offline
  - platform: template
    sensors:
      bosch_hsg636xs6:
        value_template:  '{% if is_state("device_tracker.ping_bosch_hsg636xs6", "home") %} Online {% else %} Offline {%- endif %}'
      dyson_pure_cool_link:
        value_template:  '{% if is_state("device_tracker.ping_dyson_pure_cool_link", "home") %} Online {% else %} Offline {%- endif %}'
      ikea_tradfri_hub:
        value_template:  '{% if is_state("device_tracker.ping_ikea_tradfri_hub", "home") %} Online {% else %} Offline {%- endif %}'
      philips_hue_bridge:
        value_template:  '{% if is_state("device_tracker.ping_philips_hue_bridge", "home") %} Online {% else %} Offline {%- endif %}'
      raspi_homeassistant:
        value_template:  '{% if is_state("device_tracker.ping_raspi_homeassistant", "home") %} Online {% else %} Offline {%- endif %}'
      snom_d765_phone:
        value_template:  '{% if is_state("device_tracker.ping_snom_d765", "home") %} Online {% else %} Offline {%- endif %}'
      sonos_play1_kids_room:
        value_template:  '{% if is_state("device_tracker.ping_sonos_play1_kids_room", "home") %} Online {% else %} Offline {%- endif %}'
      sonos_one_bathroom:
        value_template:  '{% if is_state("device_tracker.ping_sonos_one_bathroom", "home") %} Online {% else %} Offline {%- endif %}'
      sonos_beam_living_room:
        value_template:  '{% if is_state("device_tracker.ping_sonos_beam_living_room", "home") %} Online {% else %} Offline {%- endif %}'
      sonos_play1_living_room_1:
        value_template:  '{% if is_state("device_tracker.ping_sonos_play1_living_room_1", "home") %} Online {% else %} Offline {%- endif %}'
      sonos_play1_living_room_2:
        value_template:  '{% if is_state("device_tracker.ping_sonos_play1_living_room_2", "home") %} Online {% else %} Offline {%- endif %}'
      sw02:
        value_template:  '{% if is_state("device_tracker.ping_sw02", "home") %} Online {% else %} Offline {%- endif %}'
      tv_living_room:
        value_template:  '{% if is_state("device_tracker.ping_philips_55pos9002_lan", "home") %} Online {% else %} Offline {%- endif %}'
      unifi_dream_machine_pro:
        value_template:  '{% if is_state("device_tracker.ping_unifi_dream_machine_pro", "home") %} Online {% else %} Offline {%- endif %}'
      unifi_ap_livingroom:
        value_template:  '{% if is_state("device_tracker.ping_unifi_ap_livingroom", "home") %} Online {% else %} Offline {%- endif %}'
      unifi_ap_office:
        value_template:  '{% if is_state("device_tracker.ping_unifi_ap_office", "home") %} Online {% else %} Offline {%- endif %}'
      unifi_ap_master_bedroom:
        value_template:  '{% if is_state("device_tracker.ping_unifi_ap_master_bedroom", "home") %} Online {% else %} Offline {%- endif %}'
      unifi_ap_extender:
        value_template:  '{% if is_state("device_tracker.ping_unifi_ap_extender", "home") %} Online {% else %} Offline {%- endif %}'
      unifi_switch_office:
        value_template:  '{% if is_state("device_tracker.ping_unifi_switch_office", "home") %} Online {% else %} Offline {%- endif %}'



input_text:
  network_monitoring_trigger:
    name: Network Monitoring Trigger
    initial: ""
    
automation:
  - alias: 'Network Monitoring Triggers'
    initial_state: 'true'
    trigger:
    - platform: state
      entity_id: sensor.sonos_one_bathroom
      to: 'Offline'
    - platform: state
      entity_id: sensor.sonos_play1_kids_room
      to: 'Offline'
    - platform: state
      entity_id: sensor.sonos_play1_living_room_1
      to: 'Offline'
    - platform: state
      entity_id: sensor.sonos_play1_living_room_2
      to: 'Offline'
    - platform: state
      entity_id: sensor.sonos_beam_living_room
      to: 'Offline'
    - platform: state
      entity_id: sensor.snom_d765_phone
      to: 'Offline'
    - platform: state
      entity_id: sensor.philips_hue_bridge
      to: 'Offline'
    - platform: state
      entity_id: sensor.brother_mfc_l3770cdw
      to: 'Offline'
    - platform: state
      entity_id: sensor.unifi_dream_machine_pro
      to: 'Offline'
    action:
    - service: input_text.set_value
      data_template:
        entity_id: input_text.network_monitoring_trigger
        value: >
          {% if states.input_text.network_monitoring_trigger.state|length == 0 %}
            {{ trigger.from_state.attributes.friendly_name }}
          {% elif (states.input_text.network_monitoring_trigger.state|length + trigger.from_state.attributes.friendly_name|length) < 100 %}
            {{ states.input_text.network_monitoring_trigger.state }}, {{ trigger.from_state.attributes.friendly_name }}
          {% else %}
            {{ states.input_text.network_monitoring_trigger.state }}
          {% endif %}
    - service: notify.mobile_app_iphone12pro_olbrecht_net
      data:
        title: "Network Monitoring Alert"
        message: "The device {{ states.input_text.network_monitoring_trigger.state }} is offline"
        data:
          push:
            category: monitoring
            sound:
              name: default
            thread-id: "monitoring"
            