binary_sensor:
  - platform: template
    sensors:
      everyone_home:
        friendly_name: Everyone Home
        icon_template: >-
          {% if is_state('binary_sensor.someone_home','on') %} mdi:home-account
          {% else %} mdi:home-outline
          {% endif %}
        value_template: "{{ is_state('person.jan','home') and is_state('person.kathrin','home') }}"
      someone_home:
        friendly_name: Someone Home
        icon_template: >-
          {% if is_state('binary_sensor.someone_home','on') %} mdi:home-account
          {% else %} mdi:home-outline
          {% endif %}
        value_template: "{{ is_state('person.jan','home') or is_state('person.kathrin','home') or is_state('device_tracker.mqtt_marita','home') }}"
        
        