automation:
- id: streamdeck_webhook_nonopt
  alias: "StreamDeck Webhook w/o Parameter"
  trigger:
  - platform: webhook
    webhook_id: !secret webhook_streamdeck_1
  action:
  - service_template: '{{ trigger.json.service }}'
    data_template:
      entity_id: '{{ trigger.json.entities }}'
- id: streamdeck_webhook_opt
  alias: "StreamDeck Webhook w Parameter"
  trigger:
  - platform: webhook
    webhook_id: !secret webhook_streamdeck_2
  action:
  - service_template: '{{ trigger.json.service }}'
    data_template:
      entity_id: '{{ trigger.json.entities }}'
      brightness_pct: '{{ trigger.json.parameter }}'      