input_select:
  theme:
    name: Theme
    options:
      - Default
      - Slate
      - OLED
      - Google Dark Theme
      - Google Light Theme
    initial: Default
    icon: mdi:target

automation:
  - alias: 'Themes: Enable Slate Theme'
    initial_state: 'true'
    trigger:
    - entity_id: input_select.theme
      platform: state
      to: Slate
    condition: []
    action:
    - data:
        name: slate
      service: frontend.set_theme
  - alias: 'Themes: Enable Default Theme'
    initial_state: 'true'
    trigger:
    - entity_id: input_select.theme
      platform: state
      to: Default
    condition: []
    action:
    - data:
        name: default
      service: frontend.set_theme
  - alias: 'Themes: Enable OLED Theme'
    initial_state: 'true'
    trigger:
    - entity_id: input_select.theme
      platform: state
      to: OLED
    condition: []
    action:
    - data:
        name: amoled
      service: frontend.set_theme
  - alias: 'Themes: Enable Google Dark Theme'
    initial_state: 'true'
    trigger:
    - entity_id: input_select.theme
      platform: state
      to: Google Dark Theme
    condition: []
    action:
    - data:
        name: Google Dark Theme
      service: frontend.set_theme
  - alias: 'Themes: Enable Google Light Theme'
    initial_state: 'true'
    trigger:
    - entity_id: input_select.theme
      platform: state
      to: Google Light Theme
    condition: []
    action:
    - data:
        name: Google Light Theme
      service: frontend.set_theme