input_select:
  theme:
    name: Theme
    options:
      - Default
      - Slate
      - OLED
    initial: Default
    icon: mdi:target

automation:
  - alias: 'Themes: Enable Slate Theme'
    initial_state: 'true'
    trigger:
    - entity_id: input_select.theme
      platform: state
      to: Slate
    condition: []
    action:
    - data:
        name: slate
      service: frontend.set_theme
  - alias: 'Themes: Enable Default Theme'
    initial_state: 'true'
    trigger:
    - entity_id: input_select.theme
      platform: state
      to: Default
    condition: []
    action:
    - data:
        name: default
      service: frontend.set_theme
  - alias: 'Themes: Enable OLED Theme'
    initial_state: 'true'
    trigger:
    - entity_id: input_select.theme
      platform: state
      to: OLED
    condition: []
    action:
    - data:
        name: amoled
      service: frontend.set_theme