camera:
  - platform: uvc
    nvr: 192.168.0.11
    key: !secret unifi_video_api
    name: !secret unifi_video_camera_user
    password: !secret unifi_video_camera_password
    
sensor:
# UniFi Video REST API
  - platform: rest
    name: Latest movement recorded ID
    method: GET
    resource: !secret unifi_video_recording_api
    value_template: >
      {% set last = (value_json.data | count) - 1 %}
      {{ value_json.data[last]['_id'] }}

automation:
- alias: Unifi Video - Notify on motion with attachment
  trigger:
    platform: state
    entity_id: sensor.latest_movement_recorded_id
  action:
  - service: notify.ios_jans_phone
    data_template:
      message: Motion detected at {{ now().strftime('%H:%M:%S') }}
      data:
        attachment:
          url: !secret unifi_video_attachment
          content-type: MPEG4
  - service: notify.ios_kathrins_phone
    data_template:
      message: Motion detected at {{ now().strftime('%H:%M:%S') }}
      data:
        attachment:
          url: !secret unifi_video_attachment
          content-type: MPEG4
